# Generated by Django 5.1.4 on 2026-04-14 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('disputed', 'Shikoyat'), ('resolved', 'Hal etildi')], default='pending', max_length=10, verbose_name='Holat')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('hours_per_day', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Kunlik soat')),
                ('hourly_rate', models.PositiveIntegerField(verbose_name='Soatlik narx (snapshot)')),
                ('total_amount', models.PositiveIntegerField(verbose_name='Jami summa')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Bekor qilish sababi')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'bookings',
            },
        ),
    ]
