# Generated by Django 5.1.4 on 2026-04-14 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nanny',
            field=models.ForeignKey(limit_choices_to={'role': 'nanny'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_nanny', to=settings.AUTH_USER_MODEL, verbose_name='Enaga'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_parent', to=settings.AUTH_USER_MODEL, verbose_name='Ota-ona'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['parent', 'status'], name='bookings_parent__e8a3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['nanny', 'status'], name='bookings_nanny_i_2db1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='bookings_status_605ae0_idx'),
        ),
    ]
