# Generated by Django 5.1.4 on 2026-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_details',
            field=models.JSONField(blank=True, default=dict, help_text='base, surcharge, discount breakdown', verbose_name='Narx tafsilotlari'),
        ),
    ]
