# Generated by Django 5.1.4 on 2026-04-14 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('new_booking', 'Yangi buyurtma'), ('booking_confirmed', 'Buyurtma tasdiqlandi'), ('booking_active', 'Xizmat boshlandi'), ('booking_completed', 'Xizmat yakunlandi'), ('booking_cancelled', 'Buyurtma bekor qilindi'), ('booking_disputed', 'Shikoyat ochildi'), ('booking_resolved', 'Shikoyat hal etildi'), ('payment_received', "To'lov qabul qilindi"), ('review_received', 'Yangi sharh'), ('nanny_verified', 'Profil tasdiqlandi'), ('system', 'Tizim xabari')], max_length=30, verbose_name='Tur')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'db_table': 'notifications',
            },
        ),
    ]
