# Generated by Django 5.1.4 on 2026-04-14 11:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NannyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)], verbose_name='Yosh')),
                ('experience', models.PositiveSmallIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('hourly_rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10000)], verbose_name="Soatlik narx (so'm)")),
                ('bio', models.TextField(verbose_name="O'zi haqida")),
                ('skills', models.JSONField(default=list, verbose_name="Ko'nikmalar")),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('location_name', models.CharField(max_length=200, verbose_name='Joylashuv nomi')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Reyting')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Sharhlar soni')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('suspended', 'Bloklangan')], default='active', max_length=10, verbose_name='Holat')),
            ],
            options={
                'verbose_name': 'Enaga profili',
                'verbose_name_plural': 'Enaga profillari',
                'db_table': 'nanny_profiles',
            },
        ),
    ]
