# Generated by Django 5.1.4 on 2026-04-14 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nannies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nannyprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'nanny'}, on_delete=django.db.models.deletion.CASCADE, related_name='nanny_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='nannyprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_nannies', to=settings.AUTH_USER_MODEL, verbose_name='Kim tasdiqladi'),
        ),
        migrations.AddIndex(
            model_name='nannyprofile',
            index=models.Index(fields=['status', 'is_verified'], name='nanny_profi_status_563e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='nannyprofile',
            index=models.Index(fields=['-rating'], name='nanny_profi_rating_fd49a0_idx'),
        ),
        migrations.AddIndex(
            model_name='nannyprofile',
            index=models.Index(fields=['hourly_rate'], name='nanny_profi_hourly__7b3980_idx'),
        ),
    ]
