# Generated by Django 5.1.4 on 2026-04-17 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannies', '0003_nanny_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NannyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('passport', 'Pasport'), ('certificate', 'Sertifikat'), ('medical', 'Tibbiy hujjat'), ('diploma', 'Diplom'), ('other', 'Boshqa')], max_length=20, verbose_name='Hujjat turi')),
                ('file', models.FileField(upload_to='nanny_docs/%Y/%m/', verbose_name='Fayl')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10, verbose_name='Holat')),
                ('review_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enaga hujjati',
                'verbose_name_plural': 'Enaga hujjatlari',
                'db_table': 'nanny_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='nannyavailability',
            new_name='nanny_avail_nanny_i_98e872_idx',
            old_name='nanny_avail_nanny_date_idx',
        ),
        migrations.AlterField(
            model_name='nannyavailability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='nannydocument',
            name='nanny',
            field=models.ForeignKey(limit_choices_to={'role': 'nanny'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Enaga'),
        ),
        migrations.AddField(
            model_name='nannydocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Tekshirgan'),
        ),
    ]
