# Generated by Django 5.1.4 on 2026-04-14 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum Bank')], max_length=10, verbose_name='Provider')),
                ('provider_tx_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Provider tranzaksiya ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Summa (tiyin)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=10, verbose_name='Holat')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Provider meta')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'db_table': 'payments',
                'indexes': [models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['provider', 'provider_tx_id'], name='payments_provide_e48f2a_idx')],
            },
        ),
    ]
